AWSTemplateFormatVersion: 2010-09-09
Parameters:
  GithubRepoUrl:
    Type: String
    Default: 'https://github.com/CRUKorg/psychic-winner'
  BuildSpecYml:
    Type: String
  GithubBranch:
    Type: String

Resources:
  IAMP44BCO:
    Type: 'AWS::IAM::Policy'
    Properties:
      Roles:
        - !Ref IAMRCodeBuild
      PolicyName: codebuild-1
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource:
              - !GetAtt
                - LLGCB
                - Arn
              - !Join
                - ':'
                - - !GetAtt
                    - LLGCB
                    - Arn
                  - '*'
            Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
  IAMP34SBC:
    Type: 'AWS::IAM::Policy'
    Properties:
      Roles:
        - !Ref IAMRCodeBuild
      PolicyName: codebuild-2
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: VisualEditor0
            Effect: Allow
            Action:
              - 'ec2:AttachVolume'
              - 'ec2:AuthorizeSecurityGroupIngress'
              - 'ec2:DeregisterImage'
              - 'ec2:DeleteSnapshot'
              - 'ec2:DescribeInstances'
              - 'ec2:RequestSpotInstances'
              - 'ec2:CreateKeyPair'
              - 'ec2:DescribeRegions'
              - 'ec2:CreateImage'
              - 'ec2:CopyImage'
              - 'ec2:DescribeSpotInstanceRequests'
              - 'ec2:ModifyImageAttribute'
              - 'ec2:DescribeSnapshots'
              - 'ec2:DescribeSpotPriceHistory'
              - 'ec2:DeleteVolume'
              - 'logs:CreateLogStream'
              - 'ec2:ModifySnapshotAttribute'
              - 'ec2:CreateSecurityGroup'
              - 'ec2:DescribeVolumes'
              - 'ec2:CreateSnapshot'
              - 'ec2:ModifyInstanceAttribute'
              - 'ec2:DescribeInstanceStatus'
              - 'ec2:DetachVolume'
              - 'ec2:TerminateInstances'
              - 'ec2:DescribeTags'
              - 'ec2:CreateTags'
              - 'ec2:RegisterImage'
              - 'ec2:RunInstances'
              - 's3:GetBucketAcl'
              - 'ec2:StopInstances'
              - 'logs:PutLogEvents'
              - 'ec2:DescribeSecurityGroups'
              - 'ec2:CreateVolume'
              - 'ec2:DescribeImages'
              - 's3:PutObject'
              - 's3:GetObject'
              - 'ec2:CancelSpotInstanceRequests'
              - 'ec2:GetPasswordData'
              - 'ec2:DescribeImageAttribute'
              - 'ec2:DeleteSecurityGroup'
              - 'ec2:DescribeSubnets'
              - 's3:GetBucketLocation'
              - 'ec2:DeleteKeyPair'
              - 's3:GetObjectVersion'
            Resource: '*'
          - Sid: VisualEditor1
            Effect: Allow
            Action: 'logs:CreateLogGroup'
            Resource: '*'
  CBPAMIBuilder:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      ServiceRole: !GetAtt
        - IAMRCodeBuild
        - Arn
      QueuedTimeoutInMinutes: 60
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/standard:2.0'
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
      Source:
        Type: GITHUB
        Location: !Ref GithubRepoUrl
        BuildSpec: !Ref BuildSpecYml
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: !Ref GithubBranch
      LogsConfig:
        CloudWatchLogs:
          GroupName: CodeBuild
          StreamName: AMI_Builder
          Status: ENABLED
  IAMRCodeBuild:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - 'sts:AssumeRole'
  LLGCB:
    Type: 'AWS::Logs::LogGroup'
    Properties: {}
